name: zezai

enterprise:
  name: tanwenze
  age: 20
  tel: 18273272340
---
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db1?useUnicode=true&useSSL=false&characterEncoding=UTF-8   #定义jdbc数据源,取代Spring里的Jdbc.config配置类
    username: root
    password: 123456
    type: com.alibaba.druid.pool.DruidDataSource     #使用Druid数据源
---
#设置默认环境
spring:
  profiles:
    active: dev
---
#开发环境
spring:
   config:
      activate:
        on-profile: dev
server:
  port: 8080

---
#生产环境
spring:
  config:
    activate:
      on-profile: pro
server:
  port: 8081

---
#测试环境
spring:
  config:
    activate:
      on-profile: test
server:
  port: 8082




