name: zezai

enterprise:
  name: tanwenze
  age: 20
  tel: 18273272340



#设置默认环境
spring:
  profiles:
    active: pro
---
#开发环境
spring:
  profiles: dev
server:
  port: 8080

---
#生产环境
spring:
  profiles: pro
server:
  port: 8081

---
#测试环境
spring:
  profiles: test
server:
  port: 8082




